In [ ]:
#Easy Exercises

import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
Even = a[a%2 == 0]
Sum = np.sum(a)
# print(Even) 
# print(Sum)


New_Array = a + 10
# print(New_Array)

zero_matrix = np.zeros((2,3))
zero_matrix[1,:] = [5,5,5]

# print(zero_matrix)


x = np.array([5, np.nan, 15, np.nan, 25])
x = x[~np.isnan(x)]
X_mean = np.nanmean(x)
# print(X_mean)
# print(x)


oneD = np.array([1,2,3,4,5,6])
TwoD = oneD.reshape(3,2)
# print(TwoD)




In [ ]:
#Medium Exercises

b = np.array([
 [10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]
)
MiddleColumn = b[: , 1]
# print(MiddleColumn)
Mean = np.mean(MiddleColumn)
# print(Mean)


a = np.array([100,200,300])
Added_Gst = a * 0.18
New_prices = a+ Added_Gst
# print(New_prices)


Nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])
NewNum = Nums[(Nums%3 == 0) & (Nums % 5 == 0)]
# print(NewNum)
# print(len(NewNum))

marks = np.array([
    [35, 40, 45],
    [50, np.nan, 60],
    [70, 80, 90]
])
mean_value = np.nanmean(marks)
marks[np.isnan(marks)]=mean_value

# print(marks)


A1 = np.array([1,2,3])
B1 = np.array([2,3,4])

E_W_M = A1*B1
Dot_product = A1@B1
# print(E_W_M)
# print(Dot_product)


marks2 = np.array([
    [35, 40, 45],
    [50, 45, 60],
    [70, 80, 90]
])

ColSum = np.sum(marks2,axis=0)
# print(ColSum)
RowSum = np.sum(marks2 , axis =1)
# print(RowSum)


[155 165 195]
[120 155 240]


In [51]:
#Hard Questions 

Scores = np.array([
    [20,2,35,24],
    [23,1,21,34],
    [22,1,21,45],
    [89,21,21,56],
    [22,31,23,45]
])
studentWiseAverage = np.mean(Scores , axis=1)
subwiseAverage = np.mean(Scores, axis=0)
# print(studentWiseAverage)
# print(subwiseAverage)


b = np.array([
 [10, 20],
 [40, 50],
 ]
)

a = np.array([
    [35, 40],
    [50, 45],
  
])

print(a.shape)
print(b.shape)

def Operation(a,b):
    Result = a@b.T
    
    return Result.flatten()

print(Operation(a,b))


(2, 2)
(2, 2)
[1150 3400 1400 4250]
